# Generated by Django 5.2 on 2026-08-02 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('portfolio', 'Portfolio')], default='resume', max_length=20)),
                ('object_name', models.CharField(max_length=500)),
                ('file_url', models.URLField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='resume_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='candidates.fileupload'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['user', 'file_type'], name='file_upload_user_id_3613f9_idx'),
        ),
    ]
